### ISSUE TITLE
[ETC] github release : failure 떠있음

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Frontend#1]
## 🖥️ Descriptions
 - 10.2(수) 오후 2시23분에 ci/cd github release failure 떠있는데 확인부탁드립니다
 - 제가 건든거 : 이슈 템플릿 수정했는데 그 시점 이후로 에러난거같아요 이상 있으면 이전으로 되돌려볼게요

## 📖 Research (선택)
 - [링크](https://geoseong.github.io/docs/scm/git/tagoverview)
 - '이미 존재하는 태그에 푸쉬하면 에러 뜬다'

**Comment by soseongha** [comment]
**_커밋 e9224c124d5f13c64ffa06f02bb5ce317a5d5cf1 에서 해결했습니다!_**

✅ 오류 이유: 
- release.xml의 발동 조건이 main에 push하는 것이었으므로, 승우님께서 동시에 2개의 커밋을 푸시함으로써 병렬적으로 2번의 release가 이루어짐 -> 따라서 첫 번째 커밋에 대한 릴리즈는 성공, 두번째는 실패한 것임

✅ 해결 방법:
- release.xml의 발동 조건을 'main 브랜치에 PR을 정상적으로 병합(merge)했을 때'로 수정함
- 따라서 여러 커밋을 푸시하는 본 상황에 대해 해결 + 안정성 상승
